### PR TITLE
Fix concurrent drawFrame calls

### PR DESCRIPTION
**Pull request by gcandal**

### CODE REVIEW

**Comment by gcandal** [comment]
Fixed by https://github.com/ripe-tech/ripe-sdk/commit/2d62f01353ac4de155140a2f330439b01f7f9a36

**Comment by joamag** [comment]
@gcandal I'm still "seeing" the visual issue

**Comment by gcandal** [comment]
With the latest ripe-sdk? I've never been able to reproduce it after promises were introduced (just retried doing so).

**Comment by joamag** [comment]
Yup this was fixed with the configanimate option. But not by the promises ;)

**Pull request closed without merging**
