### PR TITLE
#357 Debouncer for setting the initials

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/357 |
| Decisions | - Use debouncer timer `initialsDebounce=275` for `setInitials` and `setInitialsExtra`. <br> - Adapt tests |

Notes:
* Frontend and backend debouncer strategies were tested and had similar response times.
* Doing a debouncer within `update` was the first approach but failed to be optimal as the event `initials_extra` triggers for an `update` with a null `params.reason` and it's not possible to adapt it without a huge refactor.

### CODE REVIEW

**Review by BeeMargarida — COMMENTED** [review]
@3rdvision Just to check, did you explore a possible solution where a cancel flag is used to stop the update promise before the existence of `loadedCallback`?
For example, setting a `cancelFlag` on `cancel` that would be unset after the cancel request in update. If the flag was true during the update process (for example before `getImageUrl` or `doubleBuffer`) it would return immediately and not complete the whole update

**Comment by 3rdvision** [comment]
> Just to check, did you explore a possible solution where a cancel flag is used to stop the update promise before the existence of `loadedCallback`?

I did made an implementation of it but it didn't offer much performance difference. The problem is update will await any previous updates [here](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L1389) after it cancels pending updates [here](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L1383) and there wasn't a significant performance improvement, maybe about from 6.2s to 5.2s while using the debouncer it's about 6.2s to 3.1s.

It's also difficult to distinguish set initials update. In some places we have [reason specifying set initials](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L880) but because we also trigger [initials_extra](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L970) to notify the client that the initials changed after `setInitialsExtra`, we have a [bind for initials_extra](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/ripe.js#L211) and in other places which will do a setInitials later without including params.reason="set initials_extra" and even thought we could refactor to always track it, from what I've tried, that experience didn't hold significant performance improvements versus this one.

**Comment by BeeMargarida** [comment]
> > Just to check, did you explore a possible solution where a cancel flag is used to stop the update promise before the existence of `loadedCallback`?
> 
> I did made an implementation of it but it didn't offer much performance difference. The problem is update will await any previous updates [here](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L1389) after it cancels pending updates [here](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L1383) and there wasn't a significant performance improvement, maybe about from 6.2s to 5.2s while using the debouncer it's about 6.2s to 3.1s.
> 
> It's also difficult to distinguish set initials update. In some places we have [reason specifying set initials](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L880) but because we also trigger [initials_extra](https://github.com/ripe-tech/ripe-sdk/blob/231277f38c6546d338aa9f34f97121af17826840/src/js/base/ripe.js#L970) to notify the client that the initials changed after `setInitialsExtra`, we have a [bind for initials_extra](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/ripe.js#L211) and in other places which will do a setInitials later without including params.reason="set initials_extra" and even thought we could refactor to always track it, from what I've tried, that experience didn't hold significant performance improvements versus this one.

What I was sugesting was end the updatePromise earlier on cancel, since if the update process did yet not reach the `new Promise.....` that is saved as `loadedCallback` when the cancel is called, the whole update is made. With the approach I mentioned, this does not happen. For example, when writting a whole word, only the last request is completed (with the whole word), instead of the first and then the last.

Example inside `_update` closure in `update`: 
```
...
// verifies if the model currently loaded in the Ripe Instance can
// render the frame to be display and if that's not the case "ignores"
// the current request for update
if (frame && !this.owner.hasFrame(frame)) {
    this.trigger("not_loaded");
    return false;
}

if (this.cancelFlag) return;

// builds the URL of the image using the frame hacking approach
// this should provide us with the new values
const url = this.owner._getImageURL({
    frame: frame,
    ...
});
...

The `cancelFlag` is set as true in the `cancel` method and as false after the cancel call in `update`. If the previous update has not yet reached the assignment of `this._loadedCallback`, the `_update` method would return instead of executing until the end.

**Comment by 3rdvision** [comment]
Closing this in favor of a more performant approach https://github.com/ripe-tech/ripe-sdk/pull/366

**Pull request closed without merging**
