### PR TITLE
Fix import of logic.js

### PR DESCRIPTION
**Pull request by gcandal**
The import order matters here since `logic.js` is extending the prototype defined in `ripe.js`.

### CODE REVIEW

**Comment by joamag** [comment]
This is already fixed

**Comment by joamag** [comment]
https://github.com/ripe-tech/ripe-sdk/commit/ccc31c37e3969e620a8a9c62da7e62e9ff1a8fa3

**Comment by gcandal** [comment]
@joamag isn't the `require` missing in that commit?

**Comment by joamag** [comment]
yup you're right it's safer that way

**Pull request closed without merging**
