### PR TITLE
#132 Custom compose url

### PR DESCRIPTION
**Pull request by 3rdvision**
### Issue
- https://github.com/ripe-tech/products/issues/132

### Dependencies
- None

### Decisions
- Added `composeUrl` option to allow custom for composition endpoints

### Screenshots
- None

### CODE REVIEW

**Review by hugo-gomes — CHANGES_REQUESTED** [review]
@3rdvision add some unit tests

**Comment by 3rdvision** [comment]
> @3rdvision add some unit tests

An effective way of testing this would be to initialize ripe-sdk with a custom `composeUrl` and checking if the returned URL from `_getImageURL` would have the expected base URL.
Unfortunately, we don't do API testing in ripe-sdk so unless we change this high level decision, there's no space for a tests like these...

But this is indeed a risky change and it would be great if someone else could triple-check it.

**Review by NFSS10 — APPROVED** [review]

**Review by hugo-gomes — COMMENTED** [review]
@3rdvision I was suggesting a test in the spirit of these ones https://github.com/ripe-tech/ripe-sdk/blob/7675715d925a28a7aa2e9aa244be4728092c8b84/test/js/base/api.js#L164

just as safety check, hence a nice to have
not mandatory at all

**Comment by 3rdvision** [comment]
@hugo-gomes Can you please re-approve please?
Fixed the changelog issue link.

**Review by hugo-gomes — APPROVED** [review]

**Pull request merged**
