### PR TITLE
Fix: Override tracking info and keep other params 

### PR DESCRIPTION
**Pull request by joao-conde**
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | Other option values passed (for example `justification`) were not being propagated as expected to `setOrderStatus`. |

### CODE REVIEW

**Review by gcandal — APPROVED** [review]
@joao-conde add the fix to the changelog

**Comment by joamag** [comment]
@gcandal @joao-conde let's add the required method params explicitly

**Comment by gcandal** [comment]
> @gcandal @joao-conde let's add the required method params explicitly

@joamag wont' that be a breaking change? Also, it makes it incoherent with `cancelOrder` (e.g. https://github.com/ripe-tech/ripe-pulse/blob/fd0c1237dbb70e7356680ecd4d8acf607e9589fb/vue/components/pages/order/order-show/order-show.vue#L891)

**Comment by joao-conde** [comment]
Discussed personally:
- `setOrderStatus` takes expected fields from options and places it in params
- change all usages of methods that change order state from `{ params: {...} }` to `{...}`

**Review by gcandal — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Pull request merged**
